stages:
  - build
  - test

variables:
  IMAGE_NAME: "test-app"
  IMAGE_TAG: "latest"

build_image:
  stage: build
  script:
    - echo "Building Docker image with docker..."
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - echo "Image built successfully!"
    - docker images | grep ${IMAGE_NAME}
  only:
    - main
    - merge_requests
  tags:
    - docker

test_image:
  stage: test
  script:
    - echo "Testing the built image..."
    - docker run --rm ${IMAGE_NAME}:${IMAGE_TAG}
    - echo "Container test completed!"
  dependencies:
    - build_image
  only:
    - main
    - merge_requests
  tags:
    - docker